### PR TITLE
past events in separate page

### PR DESCRIPTION
**Pull request by sri-teja**
@shaunagm , I had separated the past events from the main page as you mentioned it was somewhat overcrowded. Is it ok?

### CODE REVIEW

**Comment by sri-teja** [comment]
Given options as in the home page like Get started , Learn more , Events buttons in the past events page also.

**Comment by shaunagm** [comment]
Hi @sri-teja.  Sorry for taking so long to reply!  I haven't merged this yet because we haven't decided yet how we want to lay out this site.  There's some other information we want to add and we're not sure what makes sense.  Once we figure that out, I'll hopefully be able to merge this (as part of additional changes).

**Comment by dcwalk** [comment]
Hi @sri-teja, we've discussed how to handle the campus.openhatch.org page and are going to modify the page in conjunction with a few other sources, unfortunately I think that means closing this pull request for now. 

The conversation has happened in openhatch/open-source-comes-to-campus#114 and openhatch/open-source-comes-to-campus#112. 

If you are still interested, do you mind commenting in one of those issues?

**Comment by sri-teja** [comment]
Its nice working with you people. I will join with in a few days. Currently
my final exams are going on.

**Pull request closed without merging**
